project:
  render:
    - tutorial.qmd
title: 'Solutions document: Using Variation in Data to Tell a Story'
format:
  html:
    output-file: "tutorial-data-variation-solutions"
    output-ext:  "html"
