project:
  render:
    - tutorial.qmd
title: 'Teaching Guide: Using Variation in Data to Tell a Story'
format:
  html:
    output-file: "tutorial-data-variation-teaching-guide"
    output-ext:  "html"
